# Generated by Django 5.2 on 2025-05-01 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='disc',
            new_name='desc',
        ),
    ]
